<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AudiolibroSeeder extends Seeder
{
    public function run()
    {
        DB::table('audiolibros')->insert([
            [
                'titulo' => 'Audiolibro 1',
                'codigo' => 'AL001',
                'autor' => 'Autor 1',
                'narrador' => 'Narrador 1',
                'tipo' => 'audiolibro',
                'categoria_id' => 1,
                'duracion' => '01:10:00',
                'portada_url' => 'https://example.com/portada_audio1.jpg',
                'audio_url' => 'https://example.com/audio1.mp3',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Audiolibro 2',
                'codigo' => 'AL002',
                'autor' => 'Autor 2',
                'narrador' => 'Narrador 2',
                'tipo' => 'audiolibro',
                'categoria_id' => 2,
                'duracion' => '01:11:00',
                'portada_url' => 'https://example.com/portada_audio2.jpg',
                'audio_url' => 'https://example.com/audio2.mp3',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Audiolibro 3',
                'codigo' => 'AL003',
                'autor' => 'Autor 3',
                'narrador' => 'Narrador 3',
                'tipo' => 'audiolibro',
                'categoria_id' => 3,
                'duracion' => '01:12:00',
                'portada_url' => 'https://example.com/portada_audio3.jpg',
                'audio_url' => 'https://example.com/audio3.mp3',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Audiolibro 4',
                'codigo' => 'AL004',
                'autor' => 'Autor 4',
                'narrador' => 'Narrador 4',
                'tipo' => 'audiolibro',
                'categoria_id' => 4,
                'duracion' => '01:13:00',
                'portada_url' => 'https://example.com/portada_audio4.jpg',
                'audio_url' => 'https://example.com/audio4.mp3',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Audiolibro 5',
                'codigo' => 'AL005',
                'autor' => 'Autor 5',
                'narrador' => 'Narrador 5',
                'tipo' => 'audiolibro',
                'categoria_id' => 5,
                'duracion' => '01:14:00',
                'portada_url' => 'https://example.com/portada_audio5.jpg',
                'audio_url' => 'https://example.com/audio5.mp3',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Audiolibro 6',
                'codigo' => 'AL006',
                'autor' => 'Autor 6',
                'narrador' => 'Narrador 6',
                'tipo' => 'audiolibro',
                'categoria_id' => 6,
                'duracion' => '01:15:00',
                'portada_url' => 'https://example.com/portada_audio6.jpg',
                'audio_url' => 'https://example.com/audio6.mp3',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Audiolibro 7',
                'codigo' => 'AL007',
                'autor' => 'Autor 7',
                'narrador' => 'Narrador 7',
                'tipo' => 'audiolibro',
                'categoria_id' => 7,
                'duracion' => '01:16:00',
                'portada_url' => 'https://example.com/portada_audio7.jpg',
                'audio_url' => 'https://example.com/audio7.mp3',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Audiolibro 8',
                'codigo' => 'AL008',
                'autor' => 'Autor 8',
                'narrador' => 'Narrador 8',
                'tipo' => 'audiolibro',
                'categoria_id' => 8,
                'duracion' => '01:17:00',
                'portada_url' => 'https://example.com/portada_audio8.jpg',
                'audio_url' => 'https://example.com/audio8.mp3',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Audiolibro 9',
                'codigo' => 'AL009',
                'autor' => 'Autor 9',
                'narrador' => 'Narrador 9',
                'tipo' => 'audiolibro',
                'categoria_id' => 9,
                'duracion' => '01:18:00',
                'portada_url' => 'https://example.com/portada_audio9.jpg',
                'audio_url' => 'https://example.com/audio9.mp3',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Audiolibro 10',
                'codigo' => 'AL010',
                'autor' => 'Autor 10',
                'narrador' => 'Narrador 10',
                'tipo' => 'audiolibro',
                'categoria_id' => 10,
                'duracion' => '01:19:00',
                'portada_url' => 'https://example.com/portada_audio10.jpg',
                'audio_url' => 'https://example.com/audio10.mp3',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Audiolibro 11',
                'codigo' => 'AL011',
                'autor' => 'Autor 11',
                'narrador' => 'Narrador 11',
                'tipo' => 'audiolibro',
                'categoria_id' => 11,
                'duracion' => '01:20:00',
                'portada_url' => 'https://example.com/portada_audio11.jpg',
                'audio_url' => 'https://example.com/audio11.mp3',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Audiolibro 12',
                'codigo' => 'AL012',
                'autor' => 'Autor 12',
                'narrador' => 'Narrador 12',
                'tipo' => 'audiolibro',
                'categoria_id' => 12,
                'duracion' => '01:21:00',
                'portada_url' => 'https://example.com/portada_audio12.jpg',
                'audio_url' => 'https://example.com/audio12.mp3',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Audiolibro 13',
                'codigo' => 'AL013',
                'autor' => 'Autor 13',
                'narrador' => 'Narrador 13',
                'tipo' => 'audiolibro',
                'categoria_id' => 13,
                'duracion' => '01:22:00',
                'portada_url' => 'https://example.com/portada_audio13.jpg',
                'audio_url' => 'https://example.com/audio13.mp3',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Audiolibro 14',
                'codigo' => 'AL014',
                'autor' => 'Autor 14',
                'narrador' => 'Narrador 14',
                'tipo' => 'audiolibro',
                'categoria_id' => 14,
                'duracion' => '01:23:00',
                'portada_url' => 'https://example.com/portada_audio14.jpg',
                'audio_url' => 'https://example.com/audio14.mp3',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Audiolibro 15',
                'codigo' => 'AL015',
                'autor' => 'Autor 15',
                'narrador' => 'Narrador 15',
                'tipo' => 'audiolibro',
                'categoria_id' => 15,
                'duracion' => '01:24:00',
                'portada_url' => 'https://example.com/portada_audio15.jpg',
                'audio_url' => 'https://example.com/audio15.mp3',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Audiolibro 16',
                'codigo' => 'AL016',
                'autor' => 'Autor 16',
                'narrador' => 'Narrador 16',
                'tipo' => 'audiolibro',
                'categoria_id' => 16,
                'duracion' => '01:25:00',
                'portada_url' => 'https://example.com/portada_audio16.jpg',
                'audio_url' => 'https://example.com/audio16.mp3',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Audiolibro 17',
                'codigo' => 'AL017',
                'autor' => 'Autor 17',
                'narrador' => 'Narrador 17',
                'tipo' => 'audiolibro',
                'categoria_id' => 17,
                'duracion' => '01:26:00',
                'portada_url' => 'https://example.com/portada_audio17.jpg',
                'audio_url' => 'https://example.com/audio17.mp3',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Audiolibro 18',
                'codigo' => 'AL018',
                'autor' => 'Autor 18',
                'narrador' => 'Narrador 18',
                'tipo' => 'audiolibro',
                'categoria_id' => 18,
                'duracion' => '01:27:00',
                'portada_url' => 'https://example.com/portada_audio18.jpg',
                'audio_url' => 'https://example.com/audio18.mp3',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Audiolibro 19',
                'codigo' => 'AL019',
                'autor' => 'Autor 19',
                'narrador' => 'Narrador 19',
                'tipo' => 'audiolibro',
                'categoria_id' => 19,
                'duracion' => '01:28:00',
                'portada_url' => 'https://example.com/portada_audio19.jpg',
                'audio_url' => 'https://example.com/audio19.mp3',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Audiolibro 20',
                'codigo' => 'AL020',
                'autor' => 'Autor 20',
                'narrador' => 'Narrador 20',
                'tipo' => 'audiolibro',
                'categoria_id' => 20,
                'duracion' => '01:29:00',
                'portada_url' => 'https://example.com/portada_audio20.jpg',
                'audio_url' => 'https://example.com/audio20.mp3',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
