<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class LibroDigitalSeeder extends Seeder
{
    public function run()
    {
        DB::table('libros_digitales')->insert([
            [
                'titulo' => 'Libro Digital 1',
                'codigo' => 'LD001',
                'autor' => 'Autor 1',
                'tipo' => 'libro',
                'categoria_id' => 1,
                'permiso_acceso' => 'publico',
                'portada_url' => 'https://example.com/portada_libro1.jpg',
                'archivo_url' => 'https://example.com/libro1.pdf',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Libro Digital 2',
                'codigo' => 'LD002',
                'autor' => 'Autor 2',
                'tipo' => 'libro',
                'categoria_id' => 2,
                'permiso_acceso' => 'publico',
                'portada_url' => 'https://example.com/portada_libro2.jpg',
                'archivo_url' => 'https://example.com/libro2.pdf',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Libro Digital 3',
                'codigo' => 'LD003',
                'autor' => 'Autor 3',
                'tipo' => 'libro',
                'categoria_id' => 3,
                'permiso_acceso' => 'publico',
                'portada_url' => 'https://example.com/portada_libro3.jpg',
                'archivo_url' => 'https://example.com/libro3.pdf',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Libro Digital 4',
                'codigo' => 'LD004',
                'autor' => 'Autor 4',
                'tipo' => 'libro',
                'categoria_id' => 4,
                'permiso_acceso' => 'publico',
                'portada_url' => 'https://example.com/portada_libro4.jpg',
                'archivo_url' => 'https://example.com/libro4.pdf',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Libro Digital 5',
                'codigo' => 'LD005',
                'autor' => 'Autor 5',
                'tipo' => 'libro',
                'categoria_id' => 5,
                'permiso_acceso' => 'publico',
                'portada_url' => 'https://example.com/portada_libro5.jpg',
                'archivo_url' => 'https://example.com/libro5.pdf',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Libro Digital 6',
                'codigo' => 'LD006',
                'autor' => 'Autor 6',
                'tipo' => 'libro',
                'categoria_id' => 6,
                'permiso_acceso' => 'publico',
                'portada_url' => 'https://example.com/portada_libro6.jpg',
                'archivo_url' => 'https://example.com/libro6.pdf',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Libro Digital 7',
                'codigo' => 'LD007',
                'autor' => 'Autor 7',
                'tipo' => 'libro',
                'categoria_id' => 7,
                'permiso_acceso' => 'publico',
                'portada_url' => 'https://example.com/portada_libro7.jpg',
                'archivo_url' => 'https://example.com/libro7.pdf',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Libro Digital 8',
                'codigo' => 'LD008',
                'autor' => 'Autor 8',
                'tipo' => 'libro',
                'categoria_id' => 8,
                'permiso_acceso' => 'publico',
                'portada_url' => 'https://example.com/portada_libro8.jpg',
                'archivo_url' => 'https://example.com/libro8.pdf',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Libro Digital 9',
                'codigo' => 'LD009',
                'autor' => 'Autor 9',
                'tipo' => 'libro',
                'categoria_id' => 9,
                'permiso_acceso' => 'publico',
                'portada_url' => 'https://example.com/portada_libro9.jpg',
                'archivo_url' => 'https://example.com/libro9.pdf',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Libro Digital 10',
                'codigo' => 'LD010',
                'autor' => 'Autor 10',
                'tipo' => 'libro',
                'categoria_id' => 10,
                'permiso_acceso' => 'publico',
                'portada_url' => 'https://example.com/portada_libro10.jpg',
                'archivo_url' => 'https://example.com/libro10.pdf',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Libro Digital 11',
                'codigo' => 'LD011',
                'autor' => 'Autor 11',
                'tipo' => 'libro',
                'categoria_id' => 11,
                'permiso_acceso' => 'publico',
                'portada_url' => 'https://example.com/portada_libro11.jpg',
                'archivo_url' => 'https://example.com/libro11.pdf',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Libro Digital 12',
                'codigo' => 'LD012',
                'autor' => 'Autor 12',
                'tipo' => 'libro',
                'categoria_id' => 12,
                'permiso_acceso' => 'publico',
                'portada_url' => 'https://example.com/portada_libro12.jpg',
                'archivo_url' => 'https://example.com/libro12.pdf',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Libro Digital 13',
                'codigo' => 'LD013',
                'autor' => 'Autor 13',
                'tipo' => 'libro',
                'categoria_id' => 13,
                'permiso_acceso' => 'publico',
                'portada_url' => 'https://example.com/portada_libro13.jpg',
                'archivo_url' => 'https://example.com/libro13.pdf',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Libro Digital 14',
                'codigo' => 'LD014',
                'autor' => 'Autor 14',
                'tipo' => 'libro',
                'categoria_id' => 14,
                'permiso_acceso' => 'publico',
                'portada_url' => 'https://example.com/portada_libro14.jpg',
                'archivo_url' => 'https://example.com/libro14.pdf',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Libro Digital 15',
                'codigo' => 'LD015',
                'autor' => 'Autor 15',
                'tipo' => 'libro',
                'categoria_id' => 15,
                'permiso_acceso' => 'publico',
                'portada_url' => 'https://example.com/portada_libro15.jpg',
                'archivo_url' => 'https://example.com/libro15.pdf',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Libro Digital 16',
                'codigo' => 'LD016',
                'autor' => 'Autor 16',
                'tipo' => 'libro',
                'categoria_id' => 16,
                'permiso_acceso' => 'publico',
                'portada_url' => 'https://example.com/portada_libro16.jpg',
                'archivo_url' => 'https://example.com/libro16.pdf',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Libro Digital 17',
                'codigo' => 'LD017',
                'autor' => 'Autor 17',
                'tipo' => 'libro',
                'categoria_id' => 17,
                'permiso_acceso' => 'publico',
                'portada_url' => 'https://example.com/portada_libro17.jpg',
                'archivo_url' => 'https://example.com/libro17.pdf',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Libro Digital 18',
                'codigo' => 'LD018',
                'autor' => 'Autor 18',
                'tipo' => 'libro',
                'categoria_id' => 18,
                'permiso_acceso' => 'publico',
                'portada_url' => 'https://example.com/portada_libro18.jpg',
                'archivo_url' => 'https://example.com/libro18.pdf',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Libro Digital 19',
                'codigo' => 'LD019',
                'autor' => 'Autor 19',
                'tipo' => 'libro',
                'categoria_id' => 19,
                'permiso_acceso' => 'publico',
                'portada_url' => 'https://example.com/portada_libro19.jpg',
                'archivo_url' => 'https://example.com/libro19.pdf',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'titulo' => 'Libro Digital 20',
                'codigo' => 'LD020',
                'autor' => 'Autor 20',
                'tipo' => 'libro',
                'categoria_id' => 20,
                'permiso_acceso' => 'publico',
                'portada_url' => 'https://example.com/portada_libro20.jpg',
                'archivo_url' => 'https://example.com/libro20.pdf',
                'estado' => 'habilitado',
                'fecha_registro' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
