<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsuarioSeeder extends Seeder
{
    public function run()
    {
        DB::table('usuarios')->insert([
            [
                'nombre_completo' => 'Usuario 1',
                'edad' => 20,
                'sexo' => 'masculino',
                'nombre_usuario' => 'user1',
                'correo' => 'user1@cubo.com',
                'rol' => 'admin',
                'numero_telefono' => '7000-1000',
                'direccion' => 'Ciudad 1',
                'estado' => 'activo',
                'contrasena' => Hash::make('password1'),
                'url_imagen' => 'https://randomuser.me/api/portraits/men/1.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],[
                'nombre_completo' => 'Usuario 2',
                'edad' => 21,
                'sexo' => 'femenino',
                'nombre_usuario' => 'user2',
                'correo' => 'user2@cubo.com',
                'rol' => 'empleado',
                'numero_telefono' => '7000-1001',
                'direccion' => 'Ciudad 2',
                'estado' => 'activo',
                'contrasena' => Hash::make('password2'),
                'url_imagen' => 'https://randomuser.me/api/portraits/women/2.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],[
                'nombre_completo' => 'Usuario 3',
                'edad' => 22,
                'sexo' => 'masculino',
                'nombre_usuario' => 'user3',
                'correo' => 'user3@cubo.com',
                'rol' => 'cliente',
                'numero_telefono' => '7000-1002',
                'direccion' => 'Ciudad 3',
                'estado' => 'activo',
                'contrasena' => Hash::make('password3'),
                'url_imagen' => 'https://randomuser.me/api/portraits/men/3.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],[
                'nombre_completo' => 'Usuario 4',
                'edad' => 23,
                'sexo' => 'femenino',
                'nombre_usuario' => 'user4',
                'correo' => 'user4@cubo.com',
                'rol' => 'admin',
                'numero_telefono' => '7000-1003',
                'direccion' => 'Ciudad 4',
                'estado' => 'activo',
                'contrasena' => Hash::make('password4'),
                'url_imagen' => 'https://randomuser.me/api/portraits/women/4.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],[
                'nombre_completo' => 'Usuario 5',
                'edad' => 24,
                'sexo' => 'masculino',
                'nombre_usuario' => 'user5',
                'correo' => 'user5@cubo.com',
                'rol' => 'empleado',
                'numero_telefono' => '7000-1004',
                'direccion' => 'Ciudad 5',
                'estado' => 'activo',
                'contrasena' => Hash::make('password5'),
                'url_imagen' => 'https://randomuser.me/api/portraits/men/5.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],[
                'nombre_completo' => 'Usuario 6',
                'edad' => 25,
                'sexo' => 'femenino',
                'nombre_usuario' => 'user6',
                'correo' => 'user6@cubo.com',
                'rol' => 'cliente',
                'numero_telefono' => '7000-1005',
                'direccion' => 'Ciudad 6',
                'estado' => 'activo',
                'contrasena' => Hash::make('password6'),
                'url_imagen' => 'https://randomuser.me/api/portraits/women/6.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],[
                'nombre_completo' => 'Usuario 7',
                'edad' => 26,
                'sexo' => 'masculino',
                'nombre_usuario' => 'user7',
                'correo' => 'user7@cubo.com',
                'rol' => 'admin',
                'numero_telefono' => '7000-1006',
                'direccion' => 'Ciudad 7',
                'estado' => 'activo',
                'contrasena' => Hash::make('password7'),
                'url_imagen' => 'https://randomuser.me/api/portraits/men/7.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],[
                'nombre_completo' => 'Usuario 8',
                'edad' => 27,
                'sexo' => 'femenino',
                'nombre_usuario' => 'user8',
                'correo' => 'user8@cubo.com',
                'rol' => 'empleado',
                'numero_telefono' => '7000-1007',
                'direccion' => 'Ciudad 8',
                'estado' => 'activo',
                'contrasena' => Hash::make('password8'),
                'url_imagen' => 'https://randomuser.me/api/portraits/women/8.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],[
                'nombre_completo' => 'Usuario 9',
                'edad' => 28,
                'sexo' => 'masculino',
                'nombre_usuario' => 'user9',
                'correo' => 'user9@cubo.com',
                'rol' => 'cliente',
                'numero_telefono' => '7000-1008',
                'direccion' => 'Ciudad 9',
                'estado' => 'activo',
                'contrasena' => Hash::make('password9'),
                'url_imagen' => 'https://randomuser.me/api/portraits/men/9.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],[
                'nombre_completo' => 'Usuario 10',
                'edad' => 29,
                'sexo' => 'femenino',
                'nombre_usuario' => 'user10',
                'correo' => 'user10@cubo.com',
                'rol' => 'admin',
                'numero_telefono' => '7000-1009',
                'direccion' => 'Ciudad 10',
                'estado' => 'activo',
                'contrasena' => Hash::make('password10'),
                'url_imagen' => 'https://randomuser.me/api/portraits/women/10.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],[
                'nombre_completo' => 'Usuario 11',
                'edad' => 20,
                'sexo' => 'masculino',
                'nombre_usuario' => 'user11',
                'correo' => 'user11@cubo.com',
                'rol' => 'empleado',
                'numero_telefono' => '7000-1010',
                'direccion' => 'Ciudad 11',
                'estado' => 'activo',
                'contrasena' => Hash::make('password11'),
                'url_imagen' => 'https://randomuser.me/api/portraits/men/11.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],[
                'nombre_completo' => 'Usuario 12',
                'edad' => 21,
                'sexo' => 'femenino',
                'nombre_usuario' => 'user12',
                'correo' => 'user12@cubo.com',
                'rol' => 'cliente',
                'numero_telefono' => '7000-1011',
                'direccion' => 'Ciudad 12',
                'estado' => 'activo',
                'contrasena' => Hash::make('password12'),
                'url_imagen' => 'https://randomuser.me/api/portraits/women/12.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],[
                'nombre_completo' => 'Usuario 13',
                'edad' => 22,
                'sexo' => 'masculino',
                'nombre_usuario' => 'user13',
                'correo' => 'user13@cubo.com',
                'rol' => 'admin',
                'numero_telefono' => '7000-1012',
                'direccion' => 'Ciudad 13',
                'estado' => 'activo',
                'contrasena' => Hash::make('password13'),
                'url_imagen' => 'https://randomuser.me/api/portraits/men/13.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],[
                'nombre_completo' => 'Usuario 14',
                'edad' => 23,
                'sexo' => 'femenino',
                'nombre_usuario' => 'user14',
                'correo' => 'user14@cubo.com',
                'rol' => 'empleado',
                'numero_telefono' => '7000-1013',
                'direccion' => 'Ciudad 14',
                'estado' => 'activo',
                'contrasena' => Hash::make('password14'),
                'url_imagen' => 'https://randomuser.me/api/portraits/women/14.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],[
                'nombre_completo' => 'Usuario 15',
                'edad' => 24,
                'sexo' => 'masculino',
                'nombre_usuario' => 'user15',
                'correo' => 'user15@cubo.com',
                'rol' => 'cliente',
                'numero_telefono' => '7000-1014',
                'direccion' => 'Ciudad 15',
                'estado' => 'activo',
                'contrasena' => Hash::make('password15'),
                'url_imagen' => 'https://randomuser.me/api/portraits/men/15.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],[
                'nombre_completo' => 'Usuario 16',
                'edad' => 25,
                'sexo' => 'femenino',
                'nombre_usuario' => 'user16',
                'correo' => 'user16@cubo.com',
                'rol' => 'admin',
                'numero_telefono' => '7000-1015',
                'direccion' => 'Ciudad 16',
                'estado' => 'activo',
                'contrasena' => Hash::make('password16'),
                'url_imagen' => 'https://randomuser.me/api/portraits/women/16.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],[
                'nombre_completo' => 'Usuario 17',
                'edad' => 26,
                'sexo' => 'masculino',
                'nombre_usuario' => 'user17',
                'correo' => 'user17@cubo.com',
                'rol' => 'empleado',
                'numero_telefono' => '7000-1016',
                'direccion' => 'Ciudad 17',
                'estado' => 'activo',
                'contrasena' => Hash::make('password17'),
                'url_imagen' => 'https://randomuser.me/api/portraits/men/17.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],[
                'nombre_completo' => 'Usuario 18',
                'edad' => 27,
                'sexo' => 'femenino',
                'nombre_usuario' => 'user18',
                'correo' => 'user18@cubo.com',
                'rol' => 'cliente',
                'numero_telefono' => '7000-1017',
                'direccion' => 'Ciudad 18',
                'estado' => 'activo',
                'contrasena' => Hash::make('password18'),
                'url_imagen' => 'https://randomuser.me/api/portraits/women/18.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],[
                'nombre_completo' => 'Usuario 19',
                'edad' => 28,
                'sexo' => 'masculino',
                'nombre_usuario' => 'user19',
                'correo' => 'user19@cubo.com',
                'rol' => 'admin',
                'numero_telefono' => '7000-1018',
                'direccion' => 'Ciudad 19',
                'estado' => 'activo',
                'contrasena' => Hash::make('password19'),
                'url_imagen' => 'https://randomuser.me/api/portraits/men/19.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ],[
                'nombre_completo' => 'Usuario 20',
                'edad' => 29,
                'sexo' => 'femenino',
                'nombre_usuario' => 'user20',
                'correo' => 'user20@cubo.com',
                'rol' => 'empleado',
                'numero_telefono' => '7000-1019',
                'direccion' => 'Ciudad 20',
                'estado' => 'activo',
                'contrasena' => Hash::make('password20'),
                'url_imagen' => 'https://randomuser.me/api/portraits/women/20.jpg',
                'created_at' => now(),
                'updated_at' => now()
            ]
        ]);
    }
}
